// <auto-generated />
using System;
using AChen.Backend.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AChen.Backend.Api.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260930124510_ActivityCsvRelease")]
    partial class ActivityCsvRelease
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.23");

            modelBuilder.Entity("AChen.Backend.Api.Features.Activities.ActivityDefinitionRecord", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<long>("ActiveVersion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DetailHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("IdentityHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MasterJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ActivityDefinitionRecord");
                });

            modelBuilder.Entity("AChen.Backend.Api.Features.Activities.ActivityOperation", b =>
                {
                    b.Property<Guid>("PlayerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PayloadHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ResponseJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("PlayerId", "RequestId");

                    b.ToTable("ActivityOperation");
                });

            modelBuilder.Entity("AChen.Backend.Api.Features.Activities.ActivityPublishedVersion", b =>
                {
                    b.Property<string>("ActivityId")
                        .HasColumnType("TEXT");

                    b.Property<long>("Version")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DetailHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MasterJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PublishedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ReleaseId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ActivityId", "Version");

                    b.ToTable("ActivityPublishedVersion");
                });

            modelBuilder.Entity("AChen.Backend.Api.Features.Activities.ActivityReleaseRecord", b =>
                {
                    b.Property<string>("ReleaseId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ManifestJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MasterJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PublishedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("Revision")
                        .HasColumnType("INTEGER");

                    b.HasKey("ReleaseId");

                    b.ToTable("ActivityReleaseRecord");
                });

            modelBuilder.Entity("AChen.Backend.Api.Features.Activities.CurrentActivityRelease", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ReleaseId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("CurrentActivityRelease");
                });

            modelBuilder.Entity("AChen.Backend.Api.Features.Activities.PlayerActivityClaim", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ActivityId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EntryId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Ordinal")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PeriodKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RewardSnapshot")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ActivityId");

                    b.HasIndex("PlayerId", "ActivityId", "EntryId", "PeriodKey", "Ordinal")
                        .IsUnique();

                    b.ToTable("PlayerActivityClaim");
                });

            modelBuilder.Entity("AChen.Backend.Api.Features.Activities.PlayerActivityCounter", b =>
                {
                    b.Property<Guid>("PlayerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ActivityId")
                        .HasColumnType("TEXT");

                    b.Property<string>("EntryId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PeriodKey")
                        .HasColumnType("TEXT");

                    b.Property<int>("Count")
                        .HasColumnType("INTEGER");

                    b.HasKey("PlayerId", "ActivityId", "EntryId", "PeriodKey");

                    b.HasIndex("ActivityId");

                    b.ToTable("PlayerActivityCounter");
                });

            modelBuilder.Entity("AChen.Backend.Api.Features.Activities.PlayerActivityPopup", b =>
                {
                    b.Property<Guid>("PlayerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ActivityId")
                        .HasColumnType("TEXT");

                    b.Property<long>("PolicyVersion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PeriodKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ShownAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("PlayerId", "ActivityId", "PolicyVersion", "PeriodKey");

                    b.HasIndex("ActivityId");

                    b.ToTable("PlayerActivityPopup");
                });

            modelBuilder.Entity("AChen.Backend.Api.Features.Activities.PlayerActivityProgress", b =>
                {
                    b.Property<Guid>("PlayerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ActivityId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Completed")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.Property<long>("Value")
                        .HasColumnType("INTEGER");

                    b.HasKey("PlayerId", "ActivityId");

                    b.HasIndex("ActivityId");

                    b.ToTable("PlayerActivityProgress");
                });

            modelBuilder.Entity("AChen.Backend.Api.Features.Activities.PlayerActivityVisit", b =>
                {
                    b.Property<Guid>("PlayerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ActivityId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ServerDay")
                        .HasColumnType("TEXT");

                    b.HasKey("PlayerId", "ActivityId", "ServerDay");

                    b.HasIndex("ActivityId");

                    b.ToTable("PlayerActivityVisit");
                });

            modelBuilder.Entity("AChen.Backend.Api.Features.Auth.RefreshSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReplacedByTokenHash")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshSessions");
                });

            modelBuilder.Entity("AChen.Backend.Api.Features.Auth.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUsername")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedUsername")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("AChen.Backend.Api.Features.ContentDelivery.CurrentContent", b =>
                {
                    b.Property<string>("Target")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ManifestJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Target");

                    b.ToTable("CurrentContents");
                });

            modelBuilder.Entity("AChen.Backend.Api.Features.Decks.PlayerDeck", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExtraDeckJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("ExtraDeck");

                    b.Property<string>("MainDeckJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("MainDeck");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("PlayerDecks");
                });

            modelBuilder.Entity("AChen.Backend.Api.Features.Players.PlayerProfile", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<int>("AvatarFrameId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AvatarId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BackgroundId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Gold")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("TEXT");

                    b.Property<string>("OwnedArtIds")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OwnedAvatarFrameIds")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OwnedAvatarIds")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OwnedBackgroundIds")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OwnedCards")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Ur")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0L);

                    b.HasKey("UserId");

                    b.ToTable("PlayerProfiles", t =>
                        {
                            t.HasCheckConstraint("CK_PlayerProfiles_Gold_NonNegative", "Gold >= 0");
                        });
                });

            modelBuilder.Entity("AChen.Backend.Api.Features.Social.FriendRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("FromUserId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ToUserId")
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FromUserId", "ToUserId");

                    b.HasIndex("ToUserId", "Status");

                    b.ToTable("FriendRequests");
                });

            modelBuilder.Entity("AChen.Backend.Api.Features.Social.Friendship", b =>
                {
                    b.Property<Guid>("UserIdA")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserIdB")
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserIdA", "UserIdB");

                    b.ToTable("Friendships");
                });

            modelBuilder.Entity("AChen.Backend.Api.Features.Social.Gift", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Cards")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Claimed")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ClaimedAt")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Gold")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("SourceUserId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TargetUserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("TitleKey")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TargetUserId", "Claimed");

                    b.ToTable("Gifts");
                });

            modelBuilder.Entity("AChen.Backend.Api.Features.Activities.ActivityPublishedVersion", b =>
                {
                    b.HasOne("AChen.Backend.Api.Features.Activities.ActivityDefinitionRecord", null)
                        .WithMany()
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AChen.Backend.Api.Features.Activities.PlayerActivityClaim", b =>
                {
                    b.HasOne("AChen.Backend.Api.Features.Activities.ActivityDefinitionRecord", null)
                        .WithMany()
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AChen.Backend.Api.Features.Activities.PlayerActivityCounter", b =>
                {
                    b.HasOne("AChen.Backend.Api.Features.Activities.ActivityDefinitionRecord", null)
                        .WithMany()
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AChen.Backend.Api.Features.Activities.PlayerActivityPopup", b =>
                {
                    b.HasOne("AChen.Backend.Api.Features.Activities.ActivityDefinitionRecord", null)
                        .WithMany()
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AChen.Backend.Api.Features.Activities.PlayerActivityProgress", b =>
                {
                    b.HasOne("AChen.Backend.Api.Features.Activities.ActivityDefinitionRecord", null)
                        .WithMany()
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AChen.Backend.Api.Features.Activities.PlayerActivityVisit", b =>
                {
                    b.HasOne("AChen.Backend.Api.Features.Activities.ActivityDefinitionRecord", null)
                        .WithMany()
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AChen.Backend.Api.Features.Auth.RefreshSession", b =>
                {
                    b.HasOne("AChen.Backend.Api.Features.Auth.User", "User")
                        .WithMany("RefreshSessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("AChen.Backend.Api.Features.Decks.PlayerDeck", b =>
                {
                    b.HasOne("AChen.Backend.Api.Features.Auth.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("AChen.Backend.Api.Features.Players.PlayerProfile", b =>
                {
                    b.HasOne("AChen.Backend.Api.Features.Auth.User", "User")
                        .WithOne("PlayerProfile")
                        .HasForeignKey("AChen.Backend.Api.Features.Players.PlayerProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("AChen.Backend.Api.Features.Auth.User", b =>
                {
                    b.Navigation("PlayerProfile");

                    b.Navigation("RefreshSessions");
                });
#pragma warning restore 612, 618
        }
    }
}
